apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: capi-project
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Namespace
  - group: ''
    kind: Secret
  - group: 'cluster.x-k8s.io'
    kind: Cluster
  - group: 'infrastructure.cluster.x-k8s.io'
    kind: ROSACluster
  - group: 'controlplane.cluster.x-k8s.io'
    kind: ROSAControlPlane
  - group: 'cluster.x-k8s.io'
    kind: MachinePool
  - group: 'infrastructure.cluster.x-k8s.io'
    kind: ROSAMachinePool
  sourceRepos:
  - '*'