---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: "rosa-hcp-1"
  namespace: "ns-rosa-hcp"
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: ROSACluster
    name: "rosa-hcp-1"
    namespace: "ns-rosa-hcp"
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: ROSAControlPlane
    name: "rosa-cp-1"
    namespace: "ns-rosa-hcp"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: ROSACluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: "rosa-hcp-1"
  namespace: "ns-rosa-hcp"
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: ROSAControlPlane
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: "rosa-cp-1"
  namespace: "ns-rosa-hcp"
spec:
#  credentialsSecretRef:
#    name: rosa-creds-secret
  rosaClusterName: rosa-hosted-control-plan-1
  domainPrefix: myhcp
  version: "4.15.20"
  region: "us-west-2"
  rolesRef:
    ingressARN: "arn:aws:iam::471112697682:role/melserng-openshift-ingress-operator-cloud-credentials"
    imageRegistryARN: "arn:aws:iam::471112697682:role/melserng-openshift-image-registry-installer-cloud-credentials"
    storageARN: "arn:aws:iam::471112697682:role/melserng-openshift-cluster-csi-drivers-ebs-cloud-credentials"
    networkARN: "arn:aws:iam::471112697682:role/melserng-openshift-cloud-network-config-controller-cloud-credent"
    kubeCloudControllerARN: "arn:aws:iam::471112697682:role/melserng-kube-system-kube-controller-manager"
    nodePoolManagementARN: "arn:aws:iam::471112697682:role/melserng-kube-system-capa-controller-manager"
    controlPlaneOperatorARN: "arn:aws:iam::471112697682:role/melserng-kube-system-control-plane-operator"
    kmsProviderARN: "arn:aws:iam::471112697682:role/melserng-kube-system-kms-provider"
  oidcID: "2a0v5hcmdvfr0e20is7nsaflaemuoo81"
  subnets:
    - "subnet-093bd43e4a1ec6509"
    #- "subnet-05e53d1f35dba030c"
    #- "subnet-0cd5f68a4ed79ee10"
    - "subnet-07f5f339a59b3e353"
    #- "subnet-0a128aea1e6d3d368"
    #- "subnet-0a53f917809985cf2"
  availabilityZones:
    - "us-west-2b"
    #- "us-west-2a"
    #- "us-west-2d"
  installerRoleARN: "arn:aws:iam::471112697682:role/melserng-HCP-ROSA-Installer-Role"
  supportRoleARN: "arn:aws:iam::471112697682:role/melserng-HCP-ROSA-Support-Role"
  workerRoleARN: "arn:aws:iam::471112697682:role/melserng-HCP-ROSA-Worker-Role"
  network:
    machineCIDR: "10.0.0.0/16"
    podCIDR: "10.128.0.0/14"
    serviceCIDR: "172.30.0.0/16"
    #networkType: Other
  defaultMachinePoolSpec:
    instanceType: "m5.xlarge"
#    autoscaling:
#      maxReplicas: 9
#      minReplicas: 1
  additionalTags:
    env: "demo"
    profile: "hcp"
  #provisionShardID: "88d699d7-7821-11ee-8b13-0a580a82022a"
# ---
# ## Extra machinepools workers
# apiVersion: cluster.x-k8s.io/v1beta1
# kind: MachinePool
# metadata:
#   annotations:
#     argocd.argoproj.io/sync-wave: "1"
#     cluster.x-k8s.io/replicas-managed-by: rosa
#   name: "workers-ex1"
#   namespace: "ns-rosa-hcp"
# spec:
#   clusterName: "rosa-hcp-1"
#   replicas: 1
#   template:
#     spec:
#       clusterName: "rosa-hcp-1"
#       bootstrap:
#         dataSecretName: ""
#       infrastructureRef:
#         name: "workers-ex1"
#         namespace: "ns-rosa-hcp"
#         apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
#         kind: ROSAMachinePool
#       nodeDeletionTimeout: 10s
# ---
# apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
# kind: ROSAMachinePool
# metadata:
#   annotations:
#     argocd.argoproj.io/sync-wave: "1"
#   name: "workers-ex1"
#   namespace: "ns-rosa-hcp"
# spec:
#   nodePoolName: "workers-ex1"
#   instanceType: "m5.xlarge"
#   labels:
#     profile: "rosa-worker-ex1"
#   subnet: "subnet-0c4115944b681cb31"
#   autoRepair: true
#   nodeDrainGracePeriod: 1m0s
#   version: "4.15.12"
#   autoscaling:
#     maxReplicas: 6
#     minReplicas: 4
#   updateConfig:
#     rollingUpdate:
#       maxUnavailable: 2
#       maxSurge: 1
#---
#apiVersion: cluster.x-k8s.io/v1beta1
#kind: MachinePool
#metadata:
#  annotations:
#    argocd.argoproj.io/sync-wave: "1"
#    cluster.x-k8s.io/replicas-managed-by: rosa
#  name: "workers-ex"
#  namespace: "ns-rosa-hcp"
#spec:
#  clusterName: "rosa-hcp-1"
#  replicas: 1
#  template:
#    spec:
#      clusterName: "rosa-hcp-1"
#      bootstrap:
#        dataSecretName: ""
#      infrastructureRef:
#        name: "workers-ex"
#        namespace: "ns-rosa-hcp"
#        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
#        kind: ROSAMachinePool
#---
#apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
#kind: ROSAMachinePool
#metadata:
#  annotations:
#    argocd.argoproj.io/sync-wave: "1"
#  name: "workers-ex"
#  namespace: "ns-rosa-hcp"
#spec:
#  nodePoolName: "workers-ex"
#  instanceType: "m5.xlarge"
#  labels:
#    profile: "rosa-worker-ex"
#  subnet: "subnet-0db61cbb0056e9cf1"
#  autoRepair: true
#  nodeDrainGracePeriod: 1m0s
#  version: "4.15.8"
#  autoscaling:
#    maxReplicas: 6
#    minReplicas: 4
#  updateConfig:
#    rollingUpdate:
#      maxUnavailable: 2
#      maxSurge: 1
#---
